/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Models.NhanVien;
import Mysql.ConnectSQL;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;


/**
 *
 * @author Computer
 */
public class frmLogin extends javax.swing.JFrame {
    ConnectSQL cn = new ConnectSQL();
    /**
     * Creates new form Login_Form
     */
    public frmLogin() {
        initComponents();
        JRootPane rp = this.getRootPane();
        rp.setDefaultButton(jButton_login);

//set icon
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_login = new javax.swing.JPanel();
        jTextField_user = new javax.swing.JTextField();
        jPasswordField_password = new javax.swing.JPasswordField();
        jLable_accName = new javax.swing.JLabel();
        jLable_password = new javax.swing.JLabel();
        jButton_login = new javax.swing.JButton();
        jLabel_cafe = new javax.swing.JLabel();
        jCheckBox_showPass = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Café Login");
        setResizable(false);

        jPanel_login.setBackground(new java.awt.Color(214, 217, 223));

        jTextField_user.setBackground(new java.awt.Color(245, 245, 245));

        jPasswordField_password.setBackground(new java.awt.Color(245, 245, 245));

        jLable_accName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLable_accName.setText("Account Name");

        jLable_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLable_password.setText("Password");

        jButton_login.setBackground(new java.awt.Color(50, 44, 36));
        jButton_login.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButton_login.setForeground(new java.awt.Color(255, 255, 255));
        jButton_login.setText("LOGIN");
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });

        jLabel_cafe.setFont(new java.awt.Font("Curlz MT", 0, 48)); // NOI18N
        jLabel_cafe.setText("CAFÉ");

        jCheckBox_showPass.setBackground(new java.awt.Color(255, 250, 250));
        jCheckBox_showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_showPassActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Hiện mật khẩu");

        javax.swing.GroupLayout jPanel_loginLayout = new javax.swing.GroupLayout(jPanel_login);
        jPanel_login.setLayout(jPanel_loginLayout);
        jPanel_loginLayout.setHorizontalGroup(
            jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_loginLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLable_accName)
                    .addComponent(jLable_password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel_loginLayout.createSequentialGroup()
                            .addComponent(jCheckBox_showPass)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTextField_user, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                        .addComponent(jPasswordField_password))
                    .addComponent(jLabel_cafe))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel_loginLayout.setVerticalGroup(
            jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_cafe)
                .addGap(18, 18, 18)
                .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_user, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLable_accName))
                .addGap(22, 22, 22)
                .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLable_password))
                .addGap(18, 18, 18)
                .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_showPass)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_showPassActionPerformed
        // TODO add your handling code here:
        if (jCheckBox_showPass.isSelected()) {
            jPasswordField_password.setEchoChar((char)0);
        } else {
            jPasswordField_password.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox_showPassActionPerformed

    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed
        // TODO add your handling code here:
        String user, pass;
        user = jTextField_user.getText();
        pass = jPasswordField_password.getText();

        NhanVien tk = new NhanVien();
        tk.setIdStaff(user);
        tk.setDob(pass);
        boolean check = cn.CheckLogin(tk);

        if(check == true){
            Run.tk = cn.GetTaiKhoan(user, pass);
            this.setVisible(false);
            Run.QLCF();
        }else{
            JOptionPane.showMessageDialog(null, "Tài khoản hoặc mật khẩu không đúng", "Login Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_loginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_login;
    private javax.swing.JCheckBox jCheckBox_showPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_cafe;
    private javax.swing.JLabel jLable_accName;
    private javax.swing.JLabel jLable_password;
    private javax.swing.JPanel jPanel_login;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JTextField jTextField_user;
    // End of variables declaration//GEN-END:variables
}
