/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.QuanLy;

import Interface.BanHang.Jp_Food;
import Models.Food;
import Mysql.ConnectSQL;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ThangIKCU
 */
public class Dl_Sua_ThucDon extends javax.swing.JDialog {
    ConnectSQL cn = new ConnectSQL();
    /**
     * Creates new form Dl_Sua_ThucDon
     */
    ArrayList<Food> td ;
    int MaMon;
    public Dl_Sua_ThucDon(java.awt.Frame parent, boolean modal, int mamon) {
        super(parent, modal);
        initComponents();
        MaMon = mamon;
        td = cn.GetFoodByMa(mamon);

        jLable_Title.setText("Sửa món - "+td.get(0).getNameFood());
        jTextField_TenMon.setText(td.get(0).getNameFood());
        jTextField_Gia.setText(String.valueOf(td.get(0).getPrice()));
        jTextField_DVT.setText(td.get(0).getDVT()); 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_Gia = new javax.swing.JTextField();
        jButton_Accept = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLable_Title = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_Exit = new javax.swing.JButton();
        jTextField_TenMon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_DVT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 2));

        jTextField_Gia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_GiaKeyReleased(evt);
            }
        });

        jButton_Accept.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Accept.setForeground(new java.awt.Color(153, 51, 0));
        jButton_Accept.setText("Xác nhận");
        jButton_Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AcceptActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 0));
        jLabel2.setText("Tên món:");

        jLable_Title.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLable_Title.setForeground(new java.awt.Color(51, 51, 0));
        jLable_Title.setText("Sửa món");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 0));
        jLabel4.setText("Đơn vị:");

        jButton_Exit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Exit.setForeground(new java.awt.Color(153, 51, 0));
        jButton_Exit.setText("Hủy");
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 0));
        jLabel3.setText("Đơn giá:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(106, 106, 106)
                            .addComponent(jButton_Accept)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton_Exit))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_TenMon, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField_DVT, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Gia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                            .addGap(22, 22, 22)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLable_Title)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLable_Title)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_TenMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_Gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_DVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Accept)
                    .addComponent(jButton_Exit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AcceptActionPerformed
        if(!validate(jTextField_TenMon,jTextField_TenMon.getText(),"Tên món")){
            return;
        }
        if(!validate(jTextField_Gia,jTextField_Gia.getText(),"Giá món")){
            return;
        }
        if(!validate(jTextField_DVT,jTextField_DVT.getText(),"Đơn vị tính")){
            return;
        }
        Food mon = new Food();
        mon.setIDFood(MaMon);
        mon.setNameFood(jTextField_TenMon.getText());
        mon.setPrice(Integer.parseInt(jTextField_Gia.getText()));
        mon.setDVT(jTextField_DVT.getText());

        int Insert = cn.UpdateFood(mon);
        if(Insert == 0){
            JOptionPane.showMessageDialog(null, "Sửa không thành công!");
            return;
        }
        Jp_QLFood.td.FillTable();
        Jp_QLFood.td.updateUI();
        try{
            Jp_Food.td.FillLoai();
            Jp_Food.td.updateUI();
        }catch(Exception e){

        }
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AcceptActionPerformed

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ExitActionPerformed

    private void jTextField_GiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_GiaKeyReleased
        try{
            Integer.parseInt(jTextField_Gia.getText());
        }catch(NumberFormatException e){
            jTextField_Gia.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_GiaKeyReleased
    private boolean validate(JTextField tf, String value, String title){
        if(value.isEmpty()){
            JOptionPane.showMessageDialog(null, title+" không được để trống !");
            tf.requestFocus();
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Accept;
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLable_Title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_DVT;
    private javax.swing.JTextField jTextField_Gia;
    private javax.swing.JTextField jTextField_TenMon;
    // End of variables declaration//GEN-END:variables
}
